"""initial schema

Revision ID: c1c57f94ee4c
Revises: 
Create Date: 2026-09-05 13:42:49.047038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c57f94ee4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conjunction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('primary_object_norad_id', sa.Integer(), nullable=False),
    sa.Column('secondary_object_norad_id', sa.Integer(), nullable=False),
    sa.Column('primary_object_name', sa.String(length=128), nullable=False),
    sa.Column('secondary_object_name', sa.String(length=128), nullable=False),
    sa.Column('tca', sa.DateTime(timezone=True), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=False),
    sa.Column('relative_velocity_km_s', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('risk_factors_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_conjunction_events_severity', 'conjunction_events', ['severity'], unique=False)
    op.create_table('removal_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('removal_priority_score', sa.Float(), nullable=False),
    sa.Column('conjunction_count', sa.Integer(), nullable=False),
    sa.Column('average_severity_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('norad_id', name='uq_removal_priority_norad_id')
    )
    op.create_table('tracked_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.Enum('ACTIVE_SATELLITE', 'DEBRIS', 'ROCKET_BODY', 'UNKNOWN', name='objecttype'), nullable=False),
    sa.Column('tle_line1', sa.String(length=80), nullable=True),
    sa.Column('tle_line2', sa.String(length=80), nullable=True),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inclination_deg', sa.Float(), nullable=False),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('raan_deg', sa.Float(), nullable=False),
    sa.Column('arg_perigee_deg', sa.Float(), nullable=False),
    sa.Column('mean_anomaly_deg', sa.Float(), nullable=False),
    sa.Column('mean_motion_rev_per_day', sa.Float(), nullable=False),
    sa.Column('bstar', sa.Float(), nullable=False),
    sa.Column('rcs_m2', sa.Float(), nullable=True),
    sa.Column('maneuverable', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('norad_id', name='uq_tracked_objects_norad_id')
    )
    op.create_index('ix_tracked_objects_object_type', 'tracked_objects', ['object_type'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conjunction_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conjunction_id'], ['conjunction_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('maneuver_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conjunction_id', sa.Integer(), nullable=False),
    sa.Column('maneuvering_object_norad_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('PROGRADE', 'RETROGRADE', 'RADIAL_OUTWARD', 'RADIAL_INWARD', 'NORMAL', 'ANTI_NORMAL', name='maneuverdirection'), nullable=False),
    sa.Column('delta_v_m_s', sa.Float(), nullable=False),
    sa.Column('execute_before_tca_minutes', sa.Float(), nullable=False),
    sa.Column('original_miss_distance_km', sa.Float(), nullable=False),
    sa.Column('predicted_miss_distance_km', sa.Float(), nullable=False),
    sa.Column('original_risk_score', sa.Float(), nullable=False),
    sa.Column('predicted_risk_score', sa.Float(), nullable=False),
    sa.Column('is_decision_support_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conjunction_id'], ['conjunction_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orbital_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_object_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('x_km', sa.Float(), nullable=False),
    sa.Column('y_km', sa.Float(), nullable=False),
    sa.Column('z_km', sa.Float(), nullable=False),
    sa.Column('vx_km_s', sa.Float(), nullable=False),
    sa.Column('vy_km_s', sa.Float(), nullable=False),
    sa.Column('vz_km_s', sa.Float(), nullable=False),
    sa.Column('altitude_km', sa.Float(), nullable=False),
    sa.Column('latitude_deg', sa.Float(), nullable=True),
    sa.Column('longitude_deg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_object_id'], ['tracked_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orbital_states_object_time', 'orbital_states', ['tracked_object_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orbital_states_object_time', table_name='orbital_states')
    op.drop_table('orbital_states')
    op.drop_table('maneuver_recommendations')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_tracked_objects_object_type', table_name='tracked_objects')
    op.drop_table('tracked_objects')
    op.drop_table('removal_priorities')
    op.drop_index('ix_conjunction_events_severity', table_name='conjunction_events')
    op.drop_table('conjunction_events')
    # ### end Alembic commands ###
